// Regenerates the glyph data from letters/*.svg. Run: node scripts/gen.mjs
//
// The sources are already cropped to their ink and use fill="currentColor", so nothing is
// transformed here. Three outputs, from one source:
//
//   src/dims.js     viewBoxes only, ~1KB    — ships eagerly, so a glyph's box is known
//                                             before its chunk arrives
//   src/glyphs/<KEY>.js  one glyph per module — [viewBox, innerSVG]
//   src/glyphs/index.js  key -> () => import() — an explicit map bundlers can split
//   src/glyphs.js   a re-export barrel      — named imports the static entry can shake
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const glyphs = readdirSync('letters')
  .filter(f => /^[A-Z]_[1-9]\.svg$/.test(f))
  .sort()
  .map(file => {
    const svg = readFileSync(`letters/${file}`, 'utf8');
    return {
      key: file[0] + file[2],
      viewBox: svg.match(/viewBox="([^"]*)"/)[1],
      inner: svg.slice(svg.indexOf('>') + 1, svg.lastIndexOf('</svg>')),
    };
  });

const header = '// Generated by scripts/gen.mjs — do not edit.\n';

writeFileSync('src/dims.js', header + '// key -> viewBox\nexport default {\n' +
  glyphs.map(g => `${g.key}:${JSON.stringify(g.viewBox)}`).join(',\n') + '\n};\n');

rmSync('src/glyphs', { recursive: true, force: true });
mkdirSync('src/glyphs');
for (const g of glyphs)
  writeFileSync(`src/glyphs/${g.key}.js`,
    `export default [${JSON.stringify(g.viewBox)},${JSON.stringify(g.inner)}];\n`);
writeFileSync('src/glyphs/index.js', header + 'export default {\n' +
  glyphs.map(g => `  ${g.key}: () => import('./${g.key}.js')`).join(',\n') + '\n};\n');

writeFileSync('src/glyphs.js', header +
  glyphs.map(g => `export { default as ${g.key} } from './glyphs/${g.key}.js';`).join('\n') + '\n');

console.log(`wrote src/dims.js, src/glyphs.js and src/glyphs/ (${glyphs.length} chunks)`);
